### ISSUE TITLE
React usePage Hook inside Modal not working

### ISSUE THREAD

**Issue by matteogilioli** [inertiaui/modal#15]
I saw that you were working with the usePage() hook from the Pull Requests, however at the moment it doesn't work inside the modal, I don't know if you are aware of that.

**Comment by pascalbaljet** [comment]
Fixed in v0.5 :)

**Comment by matteogilioli** [comment]
@pascalbaljet 

Now it works, more or less, I expected it to work another way but maybe it is the intended behavior and I had misunderstood.
I'll give you an example:

I have the Users page (users.index) calling UserForm with the route (users.create). UserForm contains the Modal of inertiaui, and inside the Modal there are other one or more components. In these components I use usePage() but I get the data from the Users page (users.index) not from UserForm (users.create), i.e. the props are from the page from which the modal is opened not from the modal page itself. 

Obviously you can give them manually from UserForm to the other internal components, however if there are many it is inconvenient.

**Comment by pascalbaljet** [comment]
I think it's already available on the `modelContext` object, but I'll introduce a `useModal()` method that works like `usePage()`, but for the current modal.

**Comment by pascalbaljet** [comment]
The `useModal()` helper has been added in v0.6: https://inertiaui.com/inertia-modal/docs/modal-props
