### ISSUE TITLE
Navigate doesn't work with visitModal

### ISSUE THREAD

**Issue by michielkempen** [inertiaui/modal#19]
I just tried out v0.5.2 of this package in my Inertia v1.3 / Vue 3.4 app and bumped into a problem related to the modal's navigate functionality.

When I use the `visitModal()` function to programmatically open a modal, it doesn't respect the global `navigate` configuration option and opens the modal without changing the URL. When I use the `ModalLink` component, the navigation happens correctly.

https://github.com/user-attachments/assets/66bd92fa-e5b2-4e61-b6e7-7a47599c69cb

**Comment by pascalbaljet** [comment]
Thanks for reporting, I'll fix that soon!

**Comment by pascalbaljet** [comment]
Fixed in v0.5.3
