### ISSUE TITLE
Global config navigate: true not honoring setting

### ISSUE THREAD

**Issue by Cannonb4ll** [inertiaui/modal#35]
I am setting this in my app.js (right before the `createInertiaApp`:

```js
import { Modal, ModalLink, putConfig, renderApp } from "@inertiaui/modal-vue";
...
putConfig({
    navigate: true,
});

createInertiaApp(...)
```

To make sure all the modals are based on a URL, but it doesn't seem to honor this setting. Is there something I am missing? I am using the ModalLink component. When I add the attribute `navigate` to that, it does honor the URL setting.

**Comment by pascalbaljet** [comment]
Ah, my bad. It only worked with `putConfig('navigate', true)`. Fixed it in v0.6.1
