### ISSUE TITLE
Redirecting back to the modal, doesn't refresh data

### ISSUE THREAD

**Issue by Cannonb4ll** [inertiaui/modal#37]
This might be me, but when I redirect from a controller function back to the modal (because some piece of data has updated), it doesn't refresh.

For example:

```php
    public function install(Request $request, $id)
    {
        ...
        $model->services[] = $service;
        $model->save()
        ...

        return redirect()->route('modals.service.show', $id)->with('success', 'Service installed');
    }
```
    
When I then check the modal after the redirect, it "should" have the new data and update the UI accordingly (like `model.services.include('whatever')`) but it doesn't do that. I do see the new value coming back in the props after the redirect, but the UI doesn't seem to pick this up.

Am I missing something obvious?

EDIT: It might be worth noting, that it seems this worked yesterday with 0.6. I will run a quick test with that.

EDIT 2: Yes, can confirm, it worked before! Forcing version: `"@inertiaui/modal-vue": "0.5.4",` solves the issue, seems the 0.6.* version changed behavior? Probably inside here is what caused it: https://github.com/inertiaui/modal/pull/33/commits/d3c00f641e4f196f24bf5d09f9b0e5d54782e0c1

**Comment by pascalbaljet** [comment]
Fixed in v0.6.2
