### ISSUE TITLE
SyntaxError: Importing binding name 'useModal' is not found.

### ISSUE THREAD

**Issue by dspangenberg** [inertiaui/modal#41]
Hi Pascal,

importing useModal in 0.6.2 isn't possible.

`js
import { useModal } from '@inertiaui/modal-vue'
`

Best regards,
Danny

**Comment by dspangenberg** [comment]
With v0.7 the import is possible, but the value returned by useModal() is null.

**Comment by pascalbaljet** [comment]
Could you share the contents of the Modal component?

**Comment by dspangenberg** [comment]
Unfortunately not. I've switched for the project to react.
