### ISSUE TITLE
Refreshing page with slideover modal causes modal to become a normal modal

### ISSUE THREAD

**Issue by Cannonb4ll** [inertiaui/modal#51]
Illustrated here:

https://github.com/user-attachments/assets/499cb341-4420-4dfc-93d4-e56bb08039cf

When you have a modal as a slideover and refresh the page, it will return to an original modal.

My ModalLink is nothing more than adding the `slideover` attribute. I feel like there's some kind of configuration ability missing doing this directly on the modal component itself, right?

**Comment by Bosphoramus** [comment]
Hi @Cannonb4ll 

You have to pass "slideover" => true to the page, like this:

return intertia()->modal("YourComponent", [
    "slideover" => true,
    ...
])->baseRoute("Whatever")

**Comment by Cannonb4ll** [comment]
Wow nice, you're right, thank you! 🥰

**Comment by Bosphoramus** [comment]
@pascalbaljet I dont know if its already documented, but i cant find it in the docs

If its not, maybe we should add it more explicitly?
