### ISSUE TITLE
Create Inertia app with App component instead of parameter

### ISSUE THREAD

**Issue by Baspa** [inertiaui/modal#54]
I need to render my `<App/>` component encapsulated in multiple HOCs like this:

```jsx
<FlareErrorBoundary>
    <HotkeysProvider>
        <RecoilRoot>
            <State auth={props?.initialPage?.props?.auth}>
                <App {...props} />
            </State>
        </RecoilRoot>
    </HotkeysProvider>
</FlareErrorBoundary>
```

> This results in: `chunk-FTD5OURC.js?v=f053c4b3:20410 Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`

It seems like I cannot use the [example code](https://inertiaui.com/inertia-modal/docs/installation#inertia-js-configuration) like below:

```jsx
import { renderApp } from '@inertiaui/modal-vue'

createInertiaApp({
    setup({ el, App, props, plugin }) {
        return
            createApp({ render: renderApp(App, props) }) 
            .use(plugin)
            .mount(el)
    }
})
```

Instead of using the `App` parameter I want to use the `<App />` component like in the [InertiaJS documentation](https://inertiajs.com/client-side-setup). Because that way I can encapsulated it in the desired HOCs. Any idea on how to achieve the same result? Couldn't get it working right now.

**Comment by pascalbaljet** [comment]
Added support for this in v0.13: https://inertiaui.com/inertia-modal/docs/custom-app-mounting

**Comment by Baspa** [comment]
Great, thanks! 🙏🏼
