### ISSUE TITLE
Conflicting instructions for installation and basic usage.

### ISSUE THREAD

**Issue by cvyl** [inertiaui/modal#7]
I was reading the documentation at
https://inertiaui.com/inertia-modal/docs/installation

After installation, the basic usage instructions in the `App.js` file are conflicting. 

Install page:
```js
        return createApp({ render: () => h(ModalRoot, () => h(App, props)) }) 

```

Basic usage:

```js
        return createApp({ render: () => h(App, props) })
            .component('Modal', Modal)
            .component('ModalLink', ModalLink)
```

Attempting to combine both results in a 
`[Vue warn]: Missing required prop: "href"`

Error and makes it nonfunctional.

Is the documentation out of date? Or am I reading this wrong?
Thank you in advance

**Comment by pascalbaljet** [comment]
Thanks for reporting! Fixed in #10
