### ISSUE TITLE
Undefined array key "_inertiaui_modal" 

### ISSUE THREAD

**Issue by raftalks** [inertiaui/modal#71]
For some reason, when a modal is set with baseRoute, it seems to throw this error.
<img width="1340" alt="image" src="https://github.com/user-attachments/assets/a398c108-dfe0-4c14-96d2-7488ea3fe284" />

- Setup on Laravel version 11

**Comment by raftalks** [comment]
Not related to the package. It was caused due to Inertia::defer in a custom macro

**Comment by gainlinejono** [comment]
I had this issue, turns it if you're using an Inertia Form (useForm) and use the only: functionality it errors out!

Example.
```
form.post(route('clients.store'), {
        onSuccess: (response) => { toast.success('Client created successfully', {
            description: 'You have successfuly created ' + form.name,
            position: 'top-center'
        }); closeModal() },
        onError: () => toast.error('Client Creation Failed', {
            description: 'Unable to create client.',
            position: 'top-center'
        }),
        only: ['clients']
    });
```
